// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WilliMaps.Data;

#nullable disable

namespace WilliMaps.Migrations
{
    [DbContext(typeof(WilliMapsDbContext))]
    [Migration("20260427122046_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocationProperty", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("PropertiesId")
                        .HasColumnType("integer");

                    b.HasKey("LocationId", "PropertiesId");

                    b.HasIndex("PropertiesId");

                    b.ToTable("LocationProperty");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            PropertiesId = 1
                        },
                        new
                        {
                            LocationId = 1,
                            PropertiesId = 3
                        },
                        new
                        {
                            LocationId = 2,
                            PropertiesId = 1
                        },
                        new
                        {
                            LocationId = 2,
                            PropertiesId = 2
                        },
                        new
                        {
                            LocationId = 2,
                            PropertiesId = 4
                        },
                        new
                        {
                            LocationId = 3,
                            PropertiesId = 1
                        },
                        new
                        {
                            LocationId = 3,
                            PropertiesId = 4
                        },
                        new
                        {
                            LocationId = 4,
                            PropertiesId = 1
                        },
                        new
                        {
                            LocationId = 4,
                            PropertiesId = 3
                        },
                        new
                        {
                            LocationId = 5,
                            PropertiesId = 1
                        },
                        new
                        {
                            LocationId = 5,
                            PropertiesId = 2
                        },
                        new
                        {
                            LocationId = 5,
                            PropertiesId = 4
                        });
                });

            modelBuilder.Entity("WilliMaps.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Hamburg",
                            Street = "Vogelhüttendeich 55",
                            ZipCode = "21107"
                        },
                        new
                        {
                            Id = 2,
                            City = "Hamburg",
                            Street = "Rotenhäuser Straße 67",
                            ZipCode = "21107"
                        },
                        new
                        {
                            Id = 3,
                            City = "Hamburg",
                            Street = "Mengestraße 20",
                            ZipCode = "21107"
                        },
                        new
                        {
                            Id = 4,
                            City = "Hamburg",
                            Street = "Dresdner Straße 36",
                            ZipCode = "21107"
                        },
                        new
                        {
                            Id = 5,
                            City = "Hamburg",
                            Street = "Ernst-August-Straße 13",
                            ZipCode = "21107"
                        });
                });

            modelBuilder.Entity("WilliMaps.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WilliMaps.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#FF5733",
                            Name = "Jugendzentrum"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#3380FF",
                            Name = "Bücherhalle"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#33FF57",
                            Name = "Sportverein"
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#FF33F5",
                            Name = "Selbstorganisierter Raum"
                        });
                });

            modelBuilder.Entity("WilliMaps.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("WilliMaps.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ProcessedAt")
                        .HasColumnType("date");

                    b.Property<string>("ProcessedById")
                        .HasColumnType("text");

                    b.Property<string>("ProcessedNote")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("SubmittedAt")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProcessedById");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("WilliMaps.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CategoryId = 1,
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (10.0014 53.4965)"),
                            Description = "Offenes Jugendzentrum mit Freizeitangeboten für Jugendliche",
                            Name = "Jugendzentrum Wilhelmsburg"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            CategoryId = 2,
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (10.0089 53.4953)"),
                            Description = "Öffentliche Bücherhalle mit Lese- und Aufenthaltsbereich",
                            Name = "Bücherhalle Wilhelmsburg"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            CategoryId = 4,
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (10.0035 53.4947)"),
                            Description = "Kulturzentrum mit selbstorganisierten Angeboten für alle",
                            Name = "Kulturpalast Wilhelmsburg"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 4,
                            CategoryId = 3,
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (10.0056 53.4981)"),
                            Description = "Lokaler Fußballverein mit offenen Trainingsangeboten",
                            Name = "FC Wilhelmsburg"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 5,
                            CategoryId = 3,
                            Coordinates = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (9.9934 53.4932)"),
                            Description = "Weitläufiger Park mit kostenlosen Sport- und Freizeitflächen",
                            Name = "Inselpark Wilhelmsburg"
                        });
                });

            modelBuilder.Entity("WilliMaps.Models.OpeningTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("OpeningTimes");
                });

            modelBuilder.Entity("WilliMaps.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#00C853",
                            Name = "Kostenfrei"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#2196F3",
                            Name = "Barrierefrei"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#FF9800",
                            Name = "Altersgerecht"
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#9C27B0",
                            Name = "Für alle Geschlechter"
                        });
                });

            modelBuilder.Entity("LocationProperty", b =>
                {
                    b.HasOne("WilliMaps.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WilliMaps.Models.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WilliMaps.Models.Event", b =>
                {
                    b.HasOne("WilliMaps.Models.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WilliMaps.Models.Form", b =>
                {
                    b.HasOne("WilliMaps.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WilliMaps.Models.ApplicationUser", "ProcessedBy")
                        .WithMany()
                        .HasForeignKey("ProcessedById");

                    b.Navigation("Location");

                    b.Navigation("ProcessedBy");
                });

            modelBuilder.Entity("WilliMaps.Models.Location", b =>
                {
                    b.HasOne("WilliMaps.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WilliMaps.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WilliMaps.Models.OpeningTime", b =>
                {
                    b.HasOne("WilliMaps.Models.Location", "Location")
                        .WithMany("OpeningTimes")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WilliMaps.Models.Location", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("OpeningTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
