name: Build and Test WilliMaps

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout des Repositorys
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. .NET SDK einrichten
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'  
    # 2.5 List files
    - name: List files
      run: ls -R

    # 3. Restore für das Hauptprojekt (WilliMaps)
    - name: Restore WilliMaps
      run: dotnet restore ./WilliMaps/WilliMaps.csproj
    
    # 4 Build für Hauptprojekt
    - name: Build WilliMaps
      run: dotnet build ./WilliMaps/WilliMaps.csproj --no-restore

    # 5 Restore für Testprojekt
    # - name: Restore Willi-Maps-Test
    #  run: dotnet restore ./Willi-Maps-Test/Willi-Maps-Test.csproj
   
    # 6 Build für Testprojekt
    #- name: Build Willi-Maps-Test
    #  run: dotnet build ./Willi-Maps-Test/Willi-Maps-Test.csproj --no-restore
    
